services:
  # database:
  #   image: mongo:latest
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: mongoviope
  #     MONGO_INITDB_ROOT_PASSWORD: 0803
  frontend:
    image: ${FRONTEND_RELEASE_IMAGE}
    ports:
      - "80:3000"
    env_file:
      - .env
    restart: always
  backend:
    image: ${BACKEND_RELEASE_IMAGE}
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always
