services:
  frontend:
    image: ${FRONTEND_RELEASE_IMAGE}
    ports:
      - "8080:3000"
    env_file:
      - .env
    restart: always
  backend:
    image: ${BACKEND_RELEASE_IMAGE}
    ports:
      - "4040:5000"
    env_file:
      - .env
    restart: always
